import turtle
turtle.speed(99)

lth = input("Wpisz długość:")
order = input("Wpisz głębokość:")
lth = int(lth)
order = int(order)

def corner():
    for i in range(1):
        turtle.forward(lth)
        turtle.left(60)
        turtle.forward(order)
        turtle.right(120)
        turtle.forward(order)
        turtle.left(60)
        turtle.forward(lth)
        turtle.left(60)
def star():
     for i in range(1):
        turtle.forward(order)
        turtle.left(60)
        turtle.forward(order)
        turtle.right(120)
        turtle.forward(order)
        turtle.left(60)
        turtle.forward(order)
        turtle.right(120)
        turtle.forward(order)
        turtle.left(60)
        turtle.forward(order)
        turtle.right(120)
        turtle.forward(order)
        turtle.left(60)
        turtle.forward(order)
        turtle.left(60)
def all():
    corner()
    corner()
    star()
    corner()
    corner()
    star()
    corner()
    corner()
    star()
    star()
    star()
    corner()
    corner()
    star()
    star()
    star()
    corner()
    corner()
    star()
    star()
    star()
    all()
print(all())

turtle.mainloop()